name: Create Pull Request

on:
  push:
    branches:
      - main

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create version-bump branch if it doesn't exist
        run: |
          git fetch origin
          if ! git rev-parse --verify origin/version-bump; then
            git checkout -b version-bump
            git push origin version-bump
          else
            git checkout version-bump
          fi

      - name: Make changes
        run: |
          # Your commands to make changes go here
          echo "Making changes..."

      - name: Commit changes
        run: |
          git add .
          git commit -m "Bump version"

      - name: Push changes
        run: |
          git push origin version-bump

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: version-bump
          title: "Version Bump"
          body: "This PR bumps the version."
          base: main
