name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Bump version in pyproject.toml
      run: |
        VERSION=$(echo $GITHUB_REF | sed 's/refs\/tags\/v//')
        sed -i "s/^version = .*/version = \"$VERSION\"/" pyproject.toml
      shell: bash

    - name: Commit changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add pyproject.toml
        git commit -m "Bump version to $VERSION"

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: "Bump version to $VERSION"
        branch: version-bump
        title: "Bump version to $VERSION"
        body: "This PR bumps the version to $VERSION."
        labels: version-bump

    - name: Merge Pull Request
      uses: peter-evans/merge-pull-request@v2
      with:
        pull-request: ${{ steps.create-pull-request.outputs.pull-request-number }}
        merge-method: squash

    - name: Build package
      run: python -m build

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
