name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Bump version in pyproject.toml
      id: bump_version
      run: |
        VERSION=$(echo $GITHUB_REF | sed 's/refs\/tags\/v//')
        BRANCH_NAME="bump-version-$VERSION"
        git checkout -b $BRANCH_NAME
        sed -i "s/^version = .*/version = \"$VERSION\"/" pyproject.toml
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add pyproject.toml
        git commit -m "Bump version to $VERSION"
        git push origin $BRANCH_NAME
      shell: bash

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ steps.bump_version.outputs.BRANCH_NAME }}
        title: "Bump version to ${{ steps.bump_version.outputs.VERSION }}"
        body: "This PR bumps the version to ${{ steps.bump_version.outputs.VERSION }}."
        base: main

    - name: Build package
      if: github.event_name == 'release'
      run: python -m build

    - name: Publish package
      if: github.event_name == 'release'
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
